name: poke_api
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  retrofit: ^4.1.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  collection: 1.18.0  #https://pub.dev/packages/collection
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  retrofit_generator: 8.1.0
  hive_generator: 2.0.1

flutter:
  uses-material-design: true
